AceJobAgency/ViewModels/Login.cs
using System.ComponentModel.DataAnnotations;

namespace AceJobAgency.ViewModels
{
	public class Login
	{
		[Required]
		[DataType(DataType.EmailAddress)]
		public string Email { get; set; }
		[Required]
		[DataType(DataType.Password)]
		public string Password { get; set; }
		public bool RememberMe { get; set; }
		[Required]
		public string Token { get; set; }

	}
}

AceJobAgency/ViewModels/Register.cs
using System.ComponentModel.DataAnnotations;
using System.Text.RegularExpressions;

namespace AceJobAgency.ViewModels
{
    public class Register
    {
        [Required]
        [DataType(DataType.Text)]
        public string FirstName { get; set; }
        [Required]
		[DataType(DataType.Text)]
		public string LastName { get; set; }
        [Required]
		[DataType(DataType.Text)]
		public string Gender { get; set; }
        [Required]
		[DataType(DataType.Text)]
		public string NRIC { get; set; }

        [Required]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }
        [Required, MinLength(12, ErrorMessage ="please enter 12 character")]
        [DataType(DataType.Password)]
        public string Password { get; set; }
        [Required]
        [DataType(DataType.Password)]
        [Compare(nameof(Password), ErrorMessage = "Password and confirmation password does not match")]
        public string ConfirmPassword { get; set; }
        [Required]
        [DataType(DataType.Date)]
        public DateTime DateOfBirth { get; set; }
        [Required]
        [DataType(DataType.Upload)]
        public string Resume { get; set; }
        [Required]
        [DataType(DataType.Text)]
        public string WhoamI { get; set; }

        /*        [MaxLength(50)]
                public string? FileURL { get; set; }*/
    }
}

AceJobAgency/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace AceJobAgency.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

AceJobAgency/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AceJobAgency.Pages
{
    [Authorize]
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

AceJobAgency/Pages/Login.cshtml.cs
using AceJobAgency.Model;
using AceJobAgency.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Web;

namespace AceJobAgency.Pages
{
    public class LoginModel : PageModel
    {
		private readonly GoogleCaptchaService _GoogleCaptchaService;
		[BindProperty]
		public Login LModel { get; set; }

		private readonly SignInManager<ApplicationUser> signInManager;

		private readonly IHttpContextAccessor contxt;
		protected void btnbtn_submit_Click(object sender, EventArgs e)
		{
			LModel.Email = HttpUtility.HtmlEncode(LModel.Email);
            LModel.Password = HttpUtility.HtmlEncode(LModel.Password);
        }
        public LoginModel(SignInManager<ApplicationUser> signInManager, 
			IHttpContextAccessor httpContextAccessor, GoogleCaptchaService googleCaptchaService)
		{
			this.signInManager = signInManager;
			_GoogleCaptchaService = googleCaptchaService;
			contxt = httpContextAccessor;
		}
		public void OnGet()
		{
		}

		public async Task<IActionResult> OnPostAsync()
		{
			var _GoogleCaptcha = _GoogleCaptchaService.ResVer(LModel.Token);
			if (!_GoogleCaptcha.Result.success && _GoogleCaptcha.Result.score >= 0.5)
			{
				ModelState.AddModelError("", "You are not human");

			}
			if (ModelState.IsValid)
			{
				var identityResult = await signInManager.PasswordSignInAsync(LModel.Email, LModel.Password, LModel.RememberMe, false);
				
				if (identityResult.Succeeded)
				{
	
					return RedirectToPage("Index");

				}
				ModelState.AddModelError("", "Username or Password incorrect");
			}
			return Page();
		}
	}
}

AceJobAgency/Pages/Logout.cshtml.cs
using AceJobAgency.Model;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AceJobAgency.Pages
{
    public class LogoutModel : PageModel
    {
		private readonly SignInManager<ApplicationUser> signInManager;
		public LogoutModel(SignInManager<ApplicationUser> signInManager)
		{
			this.signInManager = signInManager;
		}
		public void OnGet()
        {
        }
		public async Task<IActionResult> OnPostLogoutAsync()
		{
			await signInManager.SignOutAsync();
			return RedirectToPage("Login");
		}
		public async Task<IActionResult> OnPostDontLogoutAsync()
		{
			return RedirectToPage("Index");
		}
	}
}

AceJobAgency/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AceJobAgency.Pages
{
	[Authorize]
	public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

AceJobAgency/Pages/Register.cshtml.cs
using AceJobAgency.Model;
using AceJobAgency.ViewModels;
using Microsoft.AspNetCore.DataProtection;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AceJobAgency.Pages
{
    public class RegisterModel : PageModel
    {
        [BindProperty]
        public IFormFile? UploadFile { get; set; }
        private UserManager<ApplicationUser> userManager { get; }

        private SignInManager<ApplicationUser> signInManager { get; }

        private IWebHostEnvironment _environment;

        [BindProperty]
        public Register RModel { get; set; }

        public RegisterModel(UserManager<ApplicationUser> userManager,
        SignInManager<ApplicationUser> signInManager, IWebHostEnvironment environment)
        {
            this.userManager = userManager;
            this.signInManager = signInManager;
            _environment = environment;
        }
        public void OnGet()
        {
        }
        //Save data into the database
        public async Task<IActionResult> OnPostAsync()
        {
            if (ModelState.IsValid)
			{
                var dataProtectionProvider = DataProtectionProvider.Create("EncryptData");
                var protector = dataProtectionProvider.CreateProtector("MySecretKey");
                var user = new ApplicationUser()
                {
        
                    UserName = RModel.Email,
                    Email = RModel.Email,
					FirstName = RModel.FirstName,
                    LastName= RModel.LastName,
                    Gender= RModel.Gender,
                    NRIC= protector.Protect(RModel.NRIC),
                    DateOfBirth= RModel.DateOfBirth,
                    WhoAmI = RModel.WhoamI
                };
                var result = await userManager.CreateAsync(user, RModel.Password);
                if (result.Succeeded)
                {
                    await signInManager.SignInAsync(user, false);
                    return RedirectToPage("Index");
                }
                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }

                if(UploadFile != null)
                {
                    if(UploadFile.Length > 2 * 1024 * 1024)
                    {
                        ModelState.AddModelError("Upload", "File size cannot exceed 2MB.");
                        return Page();
                    }
                    if(UploadFile.ContentType == "application/pdf")
                    {
                        ModelState.AddModelError("Upload", "Only Allow PDF");
                        return Page();
                    }

                    var uploadsFolder = "FileUploads";
                    var resumeFile = Guid.NewGuid() + Path.GetExtension(UploadFile.FileName);

                    var resumePath = Path.Combine(_environment.ContentRootPath,"wwwroot", uploadsFolder, resumeFile);
                    using var fileStream = new FileStream(resumePath, FileMode.Create);

                    await UploadFile.CopyToAsync(fileStream);
                    RModel.Resume = string.Format("/{0}/{1}", uploadsFolder, resumeFile);
                }


            }
            return Page();
        }
    }
}

AceJobAgency/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

AceJobAgency/Pages/Login.cshtml
@page
@model AceJobAgency.Pages.LoginModel
@{
}
@using AceJobAgency;
@using Microsoft.Extensions.Options
@using Microsoft.Extensions.Configuration
@inject IOptions<GoogleCaptchaConfig> GoogleCaptchaConfig
<div class="container mt-5">

	<div class="row justify-content-center align-items-center">

		<div class="col-sm-12 col-md-12 col-lg-4">
			<h1 class="mb-3">Login </h1>

			<form method="post">
				<div asp-validation-summary="All" class="text-danger"></div>
				
				<div class="mb-3">
					<label class="form-label" asp-for="LModel.Email">Email Address</label>
					<input type="Text" asp-for="LModel.Email" class="form-control" />
					<span asp-validaton-for="LModel.Email" class="text-danger"></span>
				</div>

				<div class="mb-3">
					<label class="form-label" asp-for="LModel.Password">Password</label>
					<input type="Text" asp-for="LModel.Password" class="form-control" />
					<span asp-validaton-for="LModel.Password" class="text-danger"></span>
				</div>

				<div class="mb-3 form-check">
					<input type="checkbox" asp-for="LModel.RememberMe" class="form-check-input" />
					<label class="form-check-label" asp-for="LModel.RememberMe">Remember Me?</label>
				</div>
				<input asp-for="LModel.Token" id="LModel_Token" type="hidden" />

				<div class="mb-3">
					<button type="submit" class="btn btn-primary" id="btn_submit_Click">Login</button>
				</div>

			</form>
		</div>
	</div>
</div>

<script src="https://www.google.com/recaptcha/api.js?render=@GoogleCaptchaConfig.Value.SiteKey"></script>
<script>

	grecaptcha.ready(function () {
		grecaptcha.execute('@GoogleCaptchaConfig.Value.SiteKey', { action: 'submit' }).then(function (token) {
			console.log(token);
			$('#LModel_Token').val(token);
		});
	});

</script>

AceJobAgency/Pages/Logout.cshtml
@page
@model AceJobAgency.Pages.LogoutModel
@{
}
<form method="post">
	<div class="container mt-5">
		<div class="row justify-content-center">
			<div class="col-sm-12 col-md-12 col-lg-4">
				<p> Are you sure you want to logout? </p>
				<p> 
					<button class="btn btn-dark" asp-page-handler="Logout">Yes</button>
					<button class="btn btn-light ml-5 border-dark" asp-page-handler="DontLogout">No</button>
				</p>

			</div>
		</div>	
	</div>
</form>

AceJobAgency/Pages/Register.cshtml
@page
@model AceJobAgency.Pages.RegisterModel
@{
}
<div class="container mt-5">

	<div class="row justify-content-center align-items-center">

		<div class="col-sm-12 col-md-12 col-lg-4">
			<h1 class="mb-3">Register </h1>

			<form method="post">
				<div asp-validation-summary="All" class="text-danger"></div>
				<div class="mb-3">
					<label class="form-label" asp-for="RModel.FirstName">First Name</label>
					<input type="Text" asp-for="RModel.FirstName" class="form-control" />
					<span asp-validaton-for="RModel.FirstName" class="text-danger"></span>
				</div>
				<div class="mb-3">
					<label class="form-label" asp-for="RModel.LastName">Last Name</label>
					<input type="Text" asp-for="RModel.LastName" class="form-control" />
					<span asp-validaton-for="RModel.LastName" class="text-danger"></span>
				</div>
				<div class="col-md-6 mb-4">
					<label class="col-form-label" asp-for="RModel.Gender"></label>
					<div class="col-sm-10 d-flex align-items-center">
						<div class="form-check form-check-inline">
							@Html.RadioButtonFor(m => m.RModel.Gender, "Male",
							new {@class = "form-check-input"})
							<label class="form-check-label">Male</label>
						</div>
						<div class="form-check form-check-inline">
							@Html.RadioButtonFor(m => m.RModel.Gender, "Female",
							new {@class = "form-check-input"})
							<label class="form-check-label">Female</label>
						</div>
						<br />
						<span asp-validation-for="RModel.Gender" class="text-danger"></span>
					</div>
				</div>
				<div class="mb-3">
					<label class="form-label" asp-for="RModel.NRIC">NRIC</label>
					<input type="Text" asp-for="RModel.NRIC" class="form-control" />
					<span asp-validaton-for="RModel.NRIC" class="text-danger"></span>
				</div>
				<div class="mb-3">
					<label class="form-label" asp-for="RModel.Email">Email Address</label>
					<input type="Text" asp-for="RModel.Email" class="form-control" />
					<span asp-validaton-for="RModel.Email" class="text-danger"></span>
				</div>

				<div class="mb-3">
					<label class="form-label" asp-for="RModel.Password">Password</label>
					<input type="Text" asp-for="RModel.Password" class="form-control" />
					<span asp-validaton-for="RModel.Password" class="text-danger"></span>
				</div>

				<div class="mb-3">
					<label class="form-label" asp-for="RModel.ConfirmPassword">Confirm Password</label>
					<input type="Text" asp-for="RModel.ConfirmPassword" class="form-control" />
					<span asp-validaton-for="RModel.ConfirmPassword" class="text-danger"></span>
				</div>
				<div class="mb-3">
					<label class="form-label" asp-for="RModel.DateOfBirth">Date of Birth</label>
					<input asp-for="RModel.DateOfBirth" class="form-control" />
					<span asp-validaton-for="RModel.DateOfBirth" class="text-danger"></span>
				</div>
				<div class="mb-3">
					<label asp-for="RModel.Resume">Choose a file to upload Resume:</label><br />
					<input type="file"  class="form-control" asp-for="RModel.Resume" accept=".pdf">
					<span asp-validaton-for="RModel.Resume" class="text-danger"></span>
				</div>
				<div class="mb-3">
					<label class="form-label" asp-for="RModel.WhoamI">WhoamI</label>
					<br />
					<textarea asp-for="RModel.WhoamI" rows="10" cols="20" style="width: 100%; height: 100px; max-width: 100%;"></textarea>
					<span asp-validaton-for="RModel.WhoamI" class="text-danger"></span>
				</div>

				<div class="mb-3">
					<button ctype="submit" class="btn btn-primary">Register</button>
				</div>
			</form>
		</div>
	</div>
</div>